/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { ServiceClientOptions } from "ms-rest-js";
import * as msRest from "ms-rest-js";


/**
 * @interface
 * An interface representing LiveRequest.
 * Live Request
 *
 */
export interface LiveRequest {
  /**
   * @member {string} method Method of the Live Request.
   */
  method: string;
  /**
   * @member {string} url Url of the Live Request.
   */
  url: string;
  /**
   * @member {any} [body] Body of the Live Request
   */
  body?: any;
  /**
   * @member {any} headers Headers of the Live Request
   */
  headers: any;
  /**
   * @member {any} [query] Query Parameters of the Live Request
   */
  query?: any;
}

/**
 * @interface
 * An interface representing LiveResponse.
 * Live Response
 *
 */
export interface LiveResponse {
  /**
   * @member {string} statusCode Status code of the Response.
   */
  statusCode: string;
  /**
   * @member {any} headers Headers of the Live Response.
   */
  headers: any;
  /**
   * @member {any} [body] Body of the Live Response.
   */
  body?: any;
}

/**
 * @interface
 * An interface representing LiveValidationParameter.
 * Live Validation Parameter
 *
 */
export interface LiveValidationParameter {
  /**
   * @member {LiveRequest} liveRequest Live Request
   */
  liveRequest: LiveRequest;
  /**
   * @member {LiveResponse} liveResponse Live Response
   */
  liveResponse: LiveResponse;
}

/**
 * @interface
 * An interface representing RequestValidationResult.
 * Validation result of the live request
 *
 */
export interface RequestValidationResult {
  /**
   * @member {any} [successfulRequest] Indicates if the request is successful
   */
  successfulRequest?: any;
  /**
   * @member {any[]} [errors] List of Errors.
   */
  errors?: any[];
  /**
   * @member {any[]} [operationInfo] Operation Info
   */
  operationInfo?: any[];
}

/**
 * @interface
 * An interface representing ResponseValidationResult.
 * Validation result of the live response
 *
 */
export interface ResponseValidationResult {
  /**
   * @member {any} [successfulResponse] Indicates if the response is successful
   */
  successfulResponse?: any;
  /**
   * @member {any[]} [errors] List of Errors.
   */
  errors?: any[];
  /**
   * @member {any[]} [operationInfo] Operation Info
   */
  operationInfo?: any[];
}

/**
 * @interface
 * An interface representing LiveValidationResponse.
 * Live Validation response
 *
 */
export interface LiveValidationResponse {
  /**
   * @member {RequestValidationResult} [requestValidationResult] Validation
   * result of the live request
   */
  requestValidationResult?: RequestValidationResult;
  /**
   * @member {ResponseValidationResult} [responseValidationResult] Validation
   * result of the live response
   */
  responseValidationResult?: ResponseValidationResult;
  /**
   * @member {any[]} [errors] List of Errors.
   */
  errors?: any[];
}

/**
 * @interface
 * An interface representing LiveValidationWhiteListResponse.
 * White List Response
 *
 */
export interface LiveValidationWhiteListResponse {
  /**
   * @member {any} [safeProperties] Object that consists of several key/values.
   * Keys will be namespaces. Values will be array of resource types.
   */
  safeProperties?: any;
}

/**
 * @interface
 * An interface representing LiveValidationServiceClientOptions.
 * @extends ServiceClientOptions
 */
export interface LiveValidationServiceClientOptions extends ServiceClientOptions {
  /**
   * @member {string} [baseUri]
   */
  baseUri?: string;
}

/**
 * Contains response data for the liveValidationValidate operation.
 */
export type ToolsLiveValidationValidateResponse = LiveValidationResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LiveValidationResponse;
    };
};

/**
 * Contains response data for the liveValidationProdValidate operation.
 */
export type ToolsLiveValidationProdValidateResponse = LiveValidationResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LiveValidationResponse;
    };
};

/**
 * Contains response data for the liveValidationWhiteList operation.
 */
export type ToolsLiveValidationWhiteListResponse = LiveValidationWhiteListResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LiveValidationWhiteListResponse;
    };
};

/**
 * Contains response data for the liveValidationProdWhiteList operation.
 */
export type ToolsLiveValidationProdWhiteListResponse = LiveValidationWhiteListResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: LiveValidationWhiteListResponse;
    };
};
