/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";


export const LiveRequest: msRest.CompositeMapper = {
  serializedName: "liveRequest",
  type: {
    name: "Composite",
    className: "LiveRequest",
    modelProperties: {
      method: {
        required: true,
        serializedName: "method",
        type: {
          name: "String"
        }
      },
      url: {
        required: true,
        serializedName: "url",
        type: {
          name: "String"
        }
      },
      body: {
        serializedName: "body",
        type: {
          name: "Object"
        }
      },
      headers: {
        required: true,
        serializedName: "headers",
        type: {
          name: "Object"
        }
      },
      query: {
        serializedName: "query",
        type: {
          name: "Object"
        }
      }
    }
  }
};

export const LiveResponse: msRest.CompositeMapper = {
  serializedName: "liveResponse",
  type: {
    name: "Composite",
    className: "LiveResponse",
    modelProperties: {
      statusCode: {
        required: true,
        serializedName: "statusCode",
        type: {
          name: "String"
        }
      },
      headers: {
        required: true,
        serializedName: "headers",
        type: {
          name: "Object"
        }
      },
      body: {
        serializedName: "body",
        type: {
          name: "Object"
        }
      }
    }
  }
};

export const LiveValidationParameter: msRest.CompositeMapper = {
  serializedName: "liveValidationParameter",
  type: {
    name: "Composite",
    className: "LiveValidationParameter",
    modelProperties: {
      liveRequest: {
        required: true,
        serializedName: "liveRequest",
        type: {
          name: "Composite",
          className: "LiveRequest"
        }
      },
      liveResponse: {
        required: true,
        serializedName: "liveResponse",
        type: {
          name: "Composite",
          className: "LiveResponse"
        }
      }
    }
  }
};

export const RequestValidationResult: msRest.CompositeMapper = {
  serializedName: "requestValidationResult",
  type: {
    name: "Composite",
    className: "RequestValidationResult",
    modelProperties: {
      successfulRequest: {
        serializedName: "successfulRequest",
        type: {
          name: "Object"
        }
      },
      errors: {
        serializedName: "errors",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Object"
            }
          }
        }
      },
      operationInfo: {
        serializedName: "operationInfo",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Object"
            }
          }
        }
      }
    }
  }
};

export const ResponseValidationResult: msRest.CompositeMapper = {
  serializedName: "responseValidationResult",
  type: {
    name: "Composite",
    className: "ResponseValidationResult",
    modelProperties: {
      successfulResponse: {
        serializedName: "successfulResponse",
        type: {
          name: "Object"
        }
      },
      errors: {
        serializedName: "errors",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Object"
            }
          }
        }
      },
      operationInfo: {
        serializedName: "operationInfo",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Object"
            }
          }
        }
      }
    }
  }
};

export const LiveValidationResponse: msRest.CompositeMapper = {
  serializedName: "liveValidationResponse",
  type: {
    name: "Composite",
    className: "LiveValidationResponse",
    modelProperties: {
      requestValidationResult: {
        serializedName: "requestValidationResult",
        type: {
          name: "Composite",
          className: "RequestValidationResult"
        }
      },
      responseValidationResult: {
        serializedName: "responseValidationResult",
        type: {
          name: "Composite",
          className: "ResponseValidationResult"
        }
      },
      errors: {
        serializedName: "errors",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Object"
            }
          }
        }
      }
    }
  }
};

export const LiveValidationWhiteListResponse: msRest.CompositeMapper = {
  serializedName: "liveValidationWhiteListResponse",
  type: {
    name: "Composite",
    className: "LiveValidationWhiteListResponse",
    modelProperties: {
      safeProperties: {
        serializedName: "safeProperties",
        type: {
          name: "Object"
        }
      }
    }
  }
};
