/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";
import * as Models from "./models";

const packageName = "azure_live_validation";
const packageVersion = "0.1.0";

export class LiveValidationServiceClientContext extends msRest.ServiceClient {

  /**
   * Initializes a new instance of the LiveValidationServiceClientContext class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.LiveValidationServiceClientOptions) {

    if (!options) {
      options = {};
    }

    super(undefined, options);

    this.baseUri = options.baseUri || this.baseUri || "http://localhost:5002";
    this.requestContentType = "application/json; charset=utf-8";

    this.addUserAgentInfo(`${packageName}/${packageVersion}`);
  }
}
